name: Approve and Disapprove PRs
on:
  issue_comment:
    types: [created]

jobs:
  approve_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch PR
        id: pr
        run: |
          PR_JSON=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -X GET "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}")
          echo "::set-output name=number::$(echo "$PR_JSON" | jq -r '.number')"
          echo "::set-output name=user_login::$(echo "$PR_JSON" | jq -r '.user.login')"

      - name: Approve or Disapprove PR
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          USER_LOGIN="${{ steps.pr.outputs.user_login }}"
          if [[ "$USER_LOGIN" == "princerajpoot20" ]]; then
            for word in $COMMENT_BODY; do
              if [[ "$word" == "/approve-changes" || "$word" == "/approve" ]]; then
                curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                  -X POST "https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.pr.outputs.number }}/reviews" \
                  -d '{"event": "APPROVE", "body": "Roger that 🫡"}'
              elif [[ "$word" == "/disapprove-changes" || "$word" == "/disapprove" || "$word" == "not-approved" ]]; then
                curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                  -X POST "https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.pr.outputs.number }}/reviews" \
                  -d '{"event": "REQUEST_CHANGES", "body": "@princerajpoot20 Disapprove changes!! Try a bit harder 🙂"}'
              fi
            done
          fi
